@startuml
class DisplayContext {
    + DisplayContext(lbItalia:Label, lbRegioni:Label, lbInfo2:Label)
    + Next(lbRegioni:Label, lbInfo2:Label) : void
    + Update(lbItalia:Label, lbRegioni:Label, lbInfo2:Label) : void
    + Previous(lbRegioni:Label, lbInfo2:Label) : void
}
DisplayContext --> "O" Officina
DisplayContext --> "CurrentState" DisplayState
@enduml
