@startuml
class Positivi {
    + Positivi(O:Officina, lbRegioni:Label, lbInfo2:Label)
    + Next(ctx:DisplayContext, lbRegioni:Label, lbInfo2:Label) : void
    + UpdateState(ctx:DisplayContext, lbRegioni:Label, lbInfo2:Label) : void
    + Previous(ctx:DisplayContext, lbRegioni:Label, lbInfo2:Label) : void
}
DisplayState <|-- Positivi
Positivi --> "_O" Officina
@enduml
