@startuml
class TotaleCasi {
    + TotaleCasi(O:Officina, lbRegioni:Label, lbInfo2:Label)
    + Next(dch:DisplayChoice, lbRegioni:Label, lbInfo2:Label) : void
    + UpdateState(dch:DisplayChoice, lbRegioni:Label, lbInfo2:Label) : void
    + Previous(dch:DisplayChoice, lbRegioni:Label, lbInfo2:Label) : void
}
DisplayState <|-- TotaleCasi
TotaleCasi --> "_O" Officina
@enduml
